# Generated by Django 4.2.2 on 2023-11-14 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('otp_secret', models.CharField(max_length=200, null=True)),
                ('dummy_password', models.CharField(max_length=200, null=True)),
                ('user_type', models.CharField(choices=[('Job Seeker', 'User/Employee'), ('Employer', 'HR/Employer')], max_length=12)),
            ],
            options={
                'db_table': 'tbl_user_auth',
            },
        ),
    ]
