# Generated by Django 4.2.2 on 2023-09-27 13:41

import apps.jobs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField(default=None, max_length=500)),
                ('company_id', models.UUIDField(default=apps.jobs.models.hex_uuid, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=apps.jobs.models.hex_uuid, editable=False, primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided', max_length=500)),
                ('location', models.CharField(default=None, max_length=100)),
                ('post_date', models.DateField()),
                ('posted', models.BooleanField(default=False)),
                ('experience', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_id', models.UUIDField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyies', to='jobs.company')),
            ],
            options={
                'db_table': 'tbl_job',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=apps.jobs.models.hex_uuid, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(default=None, max_length=12, null=True)),
                ('about', models.TextField(default=None, max_length=100)),
                ('resume', models.FileField(default=None, null=True, upload_to='resume/')),
                ('profile_picture', models.FileField(default=None, null=True, upload_to='profile_picture/')),
                ('cover_letter', models.FileField(null=True, upload_to='cover_letter/')),
                ('user_type', models.CharField(choices=[('Job Seeker', 'User/Employee'), ('Employer', 'HR/Employer')], max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 'tbl_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under-reviewed', 'Under-Reviewed'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on-hold', 'On-Hold')], default='applied', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('employer_id', models.UUIDField(default=None, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.user')),
            ],
            options={
                'db_table': 'tbl_applicants',
            },
        ),
    ]
