# Generated by Django 4.2.2 on 2023-11-14 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField(default=None, max_length=500)),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=100)),
                ('description', models.TextField(default='No description provided', max_length=500)),
                ('location', models.CharField(default=None, max_length=100)),
                ('post_date', models.DateField()),
                ('posted', models.BooleanField(default=False)),
                ('experience', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_id', models.UUIDField(default=None)),
                ('job_type', models.CharField(max_length=80)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('qualifications', models.CharField(default=None, max_length=60, null=True)),
                ('vacency_position', models.IntegerField(default=0)),
                ('industry', models.CharField(default=None, max_length=50, null=True)),
                ('job_responsibilities', models.TextField(default='No Job Responsibilities provided', max_length=1000)),
                ('skills_required', models.TextField(default='No skills details provided', max_length=1000)),
                ('education_or_certifications', models.TextField(default='No Education details provided', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyies', to='jobs.company')),
            ],
            options={
                'db_table': 'tbl_job',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(default=None, max_length=100, null=True)),
                ('about', models.TextField(default=None, max_length=100, null=True)),
                ('resume', models.FileField(default=None, null=True, upload_to='resume/')),
                ('profile_picture', models.FileField(default=None, null=True, upload_to='profile_picture/')),
                ('cover_letter', models.FileField(null=True, upload_to='cover_letter/')),
                ('user_type', models.CharField(default=None, max_length=15)),
                ('experience', models.CharField(default=0, max_length=3, null=True)),
                ('qualification', models.TextField(default=None, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=6, null=True)),
                ('age', models.PositiveIntegerField(default=None, null=True)),
                ('education', models.TextField(default=None, max_length=500, null=True)),
                ('professional_skills', models.TextField(default=None, max_length=500, null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default=None, max_length=12, null=True)),
                ('website', models.URLField(default=None, null=True)),
                ('social_handles', models.URLField(default=None, null=True)),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('job', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 'tbl_user_profile',
            },
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under-reviewed', 'Under-Reviewed'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on-hold', 'On-Hold')], default='applied', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('employer_id', models.UUIDField(default=None, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.user')),
            ],
            options={
                'db_table': 'tbl_applicants',
            },
        ),
    ]
