# Generated by Django 4.2.2 on 2024-03-22 10:42

import apps.userprofile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(default=None, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=None, max_length=6, null=True)),
                ('address', models.TextField(default=None, max_length=100, null=True)),
                ('experience', models.CharField(default=0, max_length=3, null=True)),
                ('profession', models.CharField(default=None, max_length=100, null=True)),
                ('resume', models.FileField(default=None, null=True, upload_to=apps.userprofile.models.UserProfile.media_upload_path)),
                ('profile_picture', models.FileField(default=None, null=True, upload_to=apps.userprofile.models.UserProfile.media_upload_path)),
                ('cover_letter', models.FileField(null=True, upload_to=apps.userprofile.models.UserProfile.media_upload_path)),
                ('about', models.TextField(default=None, max_length=100, null=True)),
                ('education', models.JSONField(default=dict)),
                ('professional_skills', models.JSONField(default=dict)),
                ('work_experience', models.JSONField(default=dict)),
                ('phone', models.CharField(default=None, max_length=12, null=True)),
                ('website', models.URLField(default=None, null=True)),
                ('social_handles', models.URLField(default=None, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'tbl_user_profile',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorite_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'db_table': 'tbl_favorite_profiles',
            },
        ),
    ]
