# Generated by Django 4.2.2 on 2024-03-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
