# Generated by Django 4.2.2 on 2024-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professional_skills',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_experience',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
