# Generated by Django 4.2.2 on 2024-03-28 11:54

import apps.userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_letter',
            field=models.FileField(default=None, null=True, upload_to=apps.userprofile.models.UserProfile.media_upload_path),
        ),
    ]
